### ISSUE TITLE
async for_each doesnt account for remainder

### ISSUE THREAD

**Issue by EntireTwix** [EntireTwix/ThreadPool#1]
when number of elements doesn't divide into number of works, for example: 5 elements, 3 workers, having a remainder of 0.33, meaning each worker gets 1 job, and 2 elements are left unfinished.

**Comment by STBoyden** [comment]
Would rounding up in cases like these fix the issue?

**Comment by EntireTwix** [comment]
Let's say it's 2.5 jobs per thread, rounding up to 3 just goes out of range

**Comment by EntireTwix** [comment]
rounding down to 2 x 4 would only cover 8 elements

**Comment by EntireTwix** [comment]
fixed with an in retrospect easy solution
